name: Binary Ready - Veracode Static Sandbox Scanner

run-name: Binary Ready - Static Sandbox Scanner - ${{ github.event.client_payload.repository.name }}

concurrency:
  group: ${{ github.event.client_payload.event_type }}-${{ github.event.client_payload.repository.name }}-${{ github.event.client_payload.repository.branch }}
  cancel-in-progress: true

on:
  repository_dispatch:
    types: [binary-ready-veracode-sast-sandbox-scan]

jobs:
  register:
    uses: ./.github/workflows/veracode-check-run.yml
    with:
      check_run_name: ${{ github.workflow }}
      head_sha: ${{ github.event.client_payload.sha }}
      repositroy_owner: ${{ github.event.client_payload.repository.owner }}
      repositroy_name: ${{ github.event.client_payload.repository.name }}
      event_type: ${{ github.event.client_payload.event_type }}
      github_token: ${{ github.event.client_payload.token }}
      run_id: ${{ github.run_id }}
      branch: ${{ github.event.client_payload.repository.branch }}
        
  sandbox_scan:
    needs: register
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      id: download-artifact
      uses: actions/download-artifact@v4
      with:
        github-token: ${{ github.event.client_payload.token }}
        repository: ${{ github.event.client_payload.repository.full_name }}
        run-id: ${{ github.event.client_payload.run_id }}

    - name: Get the name of the downloaded files
      run: |
        artifact_file=$(ls -1 ./veracode-artifact | head -n 1)
        echo "veracode_artifact=$artifact_file" >> $GITHUB_ENV

    - name: Veracode Sandbox-Scan Action step
      id: sandbox-scan
      uses: veracode/uploadandscan-action@v0.1.2
      with:
        appname: ${{ github.event.client_payload.user_config.profile_name }}
        createprofile: true
        policy: ${{ github.event.client_payload.policy_name }}
        version: '${{ github.run_id }}'
        filepath: ./veracode-artifact/${{ env.veracode_artifact }}
        vid: '${{ secrets.VERACODE_API_ID }}'
        vkey: '${{ secrets.VERACODE_API_KEY }}'
        createsandbox: true
        sandboxname: GitHub App Scans-${{ github.event.client_payload.repository.branch }}
        include: ${{ github.event.client_payload.modules_to_scan }}
        failbuild: true
        deleteincompletescan: true
